### ISSUE TITLE
[TP2] Finish report

### ISSUE THREAD

**Issue by fdemoor** [fdemoor/CBD#2]
* Add log figures in report (in appendix for instance)
* Analyse the results: are they consistent with what was expected? Do they highlight what we wanted to observe?
* Explain in details the results for each question

**Comment by jeremyThibault** [comment]
Get to work @RemiHutin

**Comment by fdemoor** [comment]
* Question 1.1 done (please check what I did)
* Questions 1.2 and 2.1 left

**Comment by fdemoor** [comment]
We're done!
